dataset:
  type: CIFAR10
  params:
    root: data/
    train: null
    transform: null
    target_transform: null
    download: true

model:
  type: BinaryConv

  params:
    width: 32
    height: 32
    channels: &in_channels 3
    classes: &out_feature 10
    mode: &mode deterministic # stochastic or deterministic

    feature_layers:
      conv:
        - in_channels: *in_channels
          out_channels: 128
          kernel_size: 3
          stride: 1
          padding: 0
          bias: true
          padding_mode: zeros
          batch_norm: true
          activation:
            type: ReLU
            args: {}
          pool: null
          mode: *mode

        - in_channels: 128
          out_channels: 128
          kernel_size: 3
          stride: 1
          padding: 0
          bias: true
          padding_mode: zeros
          batch_norm: true
          activation:
            type: ReLU
            args: {}
          pool:
            type: MaxPool2d
            args:
              kernel_size: [2, 2]
              padding: 0
          mode: *mode

        - in_channels: 128
          out_channels: 256
          kernel_size: 3
          stride: 1
          padding: 0
          bias: true
          padding_mode: zeros
          batch_norm: true
          activation:
            type: ReLU
            args: {}
          pool: null
          mode: *mode

        - in_channels: 256
          out_channels: 256
          kernel_size: 3
          stride: 1
          padding: 0
          bias: true
          padding_mode: zeros
          batch_norm: true
          activation:
            type: ReLU
            args: {}
          pool:
            type: MaxPool2d
            args:
              kernel_size: [2, 2]
              padding: 0
          mode: *mode

        - in_channels: 256
          out_channels: 512
          kernel_size: 3
          stride: 1
          padding: 0
          bias: true
          padding_mode: zeros
          batch_norm: true
          activation:
            type: ReLU
            args: {}
          pool: null
          mode: *mode

        - in_channels: 512
          out_channels: 512
          kernel_size: 3
          stride: 1
          padding: 0
          bias: true
          padding_mode: zeros
          batch_norm: true
          activation:
            type: ReLU
            args: {}
          pool: null
          mode: *mode
      linear:
        - in_feature: 512
          out_feature: 1024
          bias: true
          batch_norm: true
          activation: null
          mode: *mode

        - in_feature: 1024
          out_feature: 1024
          bias: true
          batch_norm: true
          activation:
            type: ReLU
            args: {}
          mode: *mode

    output_layer:
      type: Linear
      args:
        in_features: 1024
        out_features: *out_feature
        bias: true

project: &project BinaryConnect
experiments: &title CIFAR10_stochastic(CONV)

runner:
  type: Runner

  dataloader:
    type: DataLoader
    params:
      num_workers: 48
      batch_size: 128 # 50 in paper

  optimizer:
    type: Adam
    params:
      # initial points
      # [0.5, 0.25, 0.1, 0.05, 0.025, 0.01]
      lr: 0.1

  scheduler: # ExponentialLR in paper
    type: ExponentialLR
    params:
      # initial points
      # [0.98, 0.97, 0.96, 0.95, 0.94, 0.93, 0.92]
      gamma: .5

    # type: StepLR
    # params:
    #   step_size: 10
    #   gamma: 0.8
    #   last_epoch: -1
    # type: MultiStepLR
    # params:
    #   milestones: [5, 10, 15, 25, 45, 50, 55, 60, 100, 200]
    #   gamma: .5
    #   last_epoch: -1
    # type: ReduceLROnPlateau
    # monitor: train_acc
    # params:
    #   mode: max
    #   factor: 0.9
    #   patience: 1
    #   threshold: 0.0004
    #   threshold_mode: rel
    #   cooldown: 0
    #   min_lr: 0
    #   eps: 0.00000008

  trainer:
    type: Trainer
    params:
      max_epochs: 1000
      gpus: -1
      distributed_backend: ddp
      fast_dev_run: false
      amp_level: "02"
      row_log_interval: 10
      weights_summary: top
      reload_dataloaders_every_epoch: false
      resume_from_checkpoint: null
      benchmark: false
      deterministic: true
      num_sanity_val_steps: 5
      overfit_batches: 0.0
      precision: 32
      profiler: true

  earlystopping:
    type: EarlyStopping
    params:
      monitor: valid/accuracy
      mode: max
      patience: 500
      verbose: True

  experiments:
    name: *title
    project_name: *project
    output_dir: output/runs
